swagger: "2.0"
info:
  description: "This is the DHBW-Project server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "0.0.1"
  title: "API Documentation with Swagger - DHBW-Project-Backend"
  contact:
    email: "info@exoplan.it"
host: "localhost"
basePath: "/"
tags:
- name: "lecturers"
  description: "Everything about your lecturer"
- name: "directorOfStudies"
  description: "Access to DirectorOfStudies"
- name: "courses"
  description: "Operations about courses"
schemes:
- "http"
paths:
  /lecturers:
    post:
      tags:
      - "lecturer"
      summary: "Add a new lecturer"
      description: ""
      operationId: "addLecturer"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "lecturer object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/lecturer"
      responses:
        201:
          description: "Lecturer successfull created"
        405:
          description: "Invalid input"
      security:
      - lecturer_auth:
        - "write:lecturers"
        - "read:lecturers"
    put:
      tags:
      - "lecturer"
      summary: "Update an existing lecturer"
      description: ""
      operationId: "updateLecturer"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "lecturer object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/lecturer"
      responses:
        201:
          description: "Lecturer successfull updated"
        400:
          description: "Invalid ID supplied"
        404:
          description: "lecturer not found"
        405:
          description: "Validation exception"
      security:
      - lecturer_auth:
        - "write:lecturers"
        - "read:lecturers"
securityDefinitions:
  lecturer_auth:
    type: "oauth2"
    authorizationUrl: "http://exoplan.it/login"
    flow: "implicit"
    scopes:
      write:lecturers: "modify lecturers in your account"
      read:lecturers: "read your lecturers"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  lecturer:
    type: "object"
    properties:
      id:
        type: "integer"
        example: 1
      academic_title:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      phonenumber:
        type: "string"
  course:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"