version: "3"
services:
  postgres:
    image: postgres:12
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_USER: ${postgres_user}
      POSTGRES_DB: becker
    networks:
      - exoplan

  pgadmin:
    image: dpage/pgadmin4:4.16
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${pgadmin_user} 
      PGADMIN_DEFAULT_PASSWORD: ${pgadmin_password}
    networks:
      - exoplan
    depends_on:
      - postgres
    ports:
      - 8080:80
    logging:
      driver: none

  exoplan-backend:
    hostname: exoplan-backend
    image: exoplan-backend
    build:
      context: ./../
      dockerfile:  ./docker/Dockerfile
    networks:
      - exoplan
    depends_on: 
      - postgres
      - pgadmin
    ports:
      - 3000:3000
    command: sh -c "dockerize -wait tcp://postgres:5432 -timeout 300s -wait-retry-interval 5s node app.js"

  nginx: 
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    volumes:
      - ./nginx_frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    networks:
     - exoplan
    depends_on: 
     - exoplan-backend
    restart: always

networks:
  exoplan: