version: "3"
services:
  postgres:
    image: postgres:12
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_USER: ${postgres_user}
      POSTGRES_DB: backend
    ports:
        5432:5432  
    networks:
      - dhbw-project-backend
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4:4.16
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${pgadmin_user} 
      PGADMIN_DEFAULT_PASSWORD: ${pgadmin_password}
    networks:
      - dhbw-project-backend
    depends_on:
      - postgres
    ports:
      - 8080:80
    logging:
      driver: none

networks:
  dhbw-project-backend: